# Generated by Django 2.1.1 on 2018-09-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome do evento')),
                ('data_de_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início do evento')),
                ('data_de_termino', models.DateField(blank=True, null=True, verbose_name='Data de término do evento')),
                ('prazo_para_submicao_de_artigos', models.DurationField(blank=True, null=True, verbose_name='Prazo para submissão de artigos')),
                ('url_do_site_do_evento', models.URLField()),
            ],
        ),
    ]
